apiVersion: v1
kind: Service
metadata:
  name: java-mysql-vaullt-demo-svc
  labels:
    name: java-mysql-vaullt-demo-svc
    purpose: demo
    env: dev
spec:
  type: NodePort
  ports:
    - name: app-port
      targetPort: 8080
      port: 80
      protocol: TCP
  selector:
    name: java-mysql-vaullt-demo-pod
    env: dev
    purpose: demo

