apiVersion: v1
kind: Pod
metadata:
  name: multi-container-app-cache-pod
  labels:
    name: multi-container-cache-pod
    env: dev
    purpose: learning
spec:
  # secret management using k8s cred store
  imagePullSecrets:
    - name: regcred
    # redis container of pod
  containers:
    - image: redis
      name: redis
      resources:
          requests:
            cpu: "250m"
            memory: "250Mi"
          limits:
            cpu: "500m"
            memory: "500Mi"
      ports:
        - containerPort: 6379
        # app container of pod
    - image: sunilmamillapalli/k8s-learning:web-cache-db
      name: custom-app-image
      resources:
        requests:
          cpu: "250m"
          memory: "250Mi"
        limits:
          cpu: "500m"
          memory: "500Mi"
      ports:
        - containerPort: 5000
