apiVersion: v1
kind: Service
metadata:
  name: app-cache-svc
  labels:
    name: app-cache-svc
    purpose: learning
    env: dev
spec:
  type: NodePort
  # redis shares common networking/disk with app container. No explicit service creation required.
  ports:
    - name: app-port
      targetPort: 5000
      port: 80
      protocol: TCP
  selector:
    name: multi-container-cache-pod
    env: dev
    purpose: learning

