apiVersion: v1
kind: ReplicationController
metadata:
  name: multi-container-app-cache-rc
  labels:
    name: multi-container-cache-pod-rc
    env: dev
    purpose: learning
spec:
  replicas: 1
  template:
    spec:
      serviceAccountName: internal-app
      imagePullSecrets:
        - name: regcred
      containers:
        - name: web-container
          image:  sunilmamillapalli/k8s-learning:web-cache-vault-support
          ports:
            - name: web-app-port
              containerPort: 5000
          resources:
            requests:
              memory: "128Mi"
              cpu: "128m"
            limits:
              memory: "256Mi"
              cpu: "256m"
        - name: redis-container
          image: redis
          ports:
            - name: redis-port
              containerPort: 6379
          resources:
            requests:
              memory: "128Mi"
              cpu: "128m"
            limits:
              memory: "256Mi"
              cpu: "256m"
    metadata:
      name: multi-container-app-cache-pod
      labels:
        name: multi-container-cache-pod
        env: dev
        purpose: learning
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/agent-inject-status: "update"
        vault.hashicorp.com/role: "internal-app"
        vault.hashicorp.com/agent-inject-secret-database-config.json: "internal/data/database/config"
        vault.hashicorp.com/agent-inject-template-database-config.json: |
          {
          {{- with secret "internal/data/database/config" -}}
          "username": "{{ .Data.data.username }}",
          "password": "{{ .Data.data.password }}"
          {{- end -}}
          }