apiVersion: v1
kind: Service
metadata:
  name: mysql
  labels:
    app: blog-app
    env: dev
    name: blog-db-svc
spec:
  type: NodePort
  ports:
    - name: mysql-port
      targetPort: 3306
      port: 3306
  selector:
    app: blog-app
    env: dev
    name: blog-db-pod